config/routes.rb
Rails.application.routes.draw do

   root 'posts#index', as: 'home'

   get 'about' => 'welcome#about', as: 'about'

resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true,
                    length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    #this will print the form data to the screen
    #render plain: params[:post].inspect
    @post = Post.new(post_params)

    if (@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
    @title = 'About this Project';
    @content = "You can blog about whatever you\'d like.
     Many choose to blog about activities they enjoy, books they love, or information that might be useful to other professionals.";
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css'%>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<ul class="nav navbar-left bg-light">
  <li class="nav-item">
    <a class="nav-link active"><%= link_to "Home", home_path %></a>
  </li>
  <li style="width:10px;"></li>
  <li class="nav-item">
    <a class="nav-link active"><%= link_to "Create Post", new_post_path %></a>
  </li>
  <li style="width:10px;"></li>
  <li class="nav-item">
    <a class="nav-link active"><%= link_to "About", about_path %></a>
  </li>
</ul>

<div class="container" style="margin-top:20px;">
    <%= yield %>
</div>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<p>Here are all of the current blog posts:</p>

<% @posts.each do |post| %>
  <h2 class="bg-info"><%= post.title %></h2>
  <p><%= post.body %></p>
<% end %>

app/views/posts/new.html.erb
<h1>Add Post</h1>
  <%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%=msg %></div>
      <% end %>
    <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'} )%>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, {:class => 'form-control'} ) %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </p>

  <% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>

app/views/welcome/about.html.erb
<h1><%=@title %></h1>
<p><%=@content %></p>